# Generated by Django 4.1.5 on 2023-07-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="vehicleSearchRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderType", models.CharField(blank=True, max_length=20)),
                ("orderNo", models.CharField(blank=True, max_length=9)),
                ("busarea", models.CharField(blank=True, max_length=10)),
                ("modelId", models.CharField(blank=True, max_length=20)),
                ("chassisNo", models.CharField(blank=True, max_length=10)),
                ("vin", models.CharField(blank=True, max_length=20)),
                ("requestedDeliveryDate", models.CharField(blank=True, max_length=10)),
                ("deliveryLocation", models.CharField(blank=True, max_length=20)),
                ("orderStatus", models.CharField(blank=True, max_length=15)),
                ("actaulDeliveryDate", models.CharField(blank=True, max_length=10)),
                ("requestedBy", models.CharField(blank=True, max_length=20)),
                ("lastOrderNo", models.CharField(blank=True, max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name="vehicleSearchResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderNo", models.IntegerField(default=0)),
                ("busarea", models.CharField(max_length=10)),
                ("modelId", models.CharField(max_length=20)),
                ("orderType", models.CharField(max_length=20)),
                ("chassisNo", models.CharField(max_length=10)),
                ("vin", models.CharField(max_length=20)),
                ("requestedDeliveryDate", models.DateField(null=True)),
                ("deliveryLocation", models.CharField(max_length=20)),
                ("orderQty", models.IntegerField(default=0)),
                (
                    "orderTotalCost",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("orderStatus", models.CharField(max_length=15)),
                ("actaulDeliveryDate", models.CharField(max_length=10, null=True)),
                ("requestedBy", models.CharField(max_length=20)),
                ("updatedBy", models.CharField(max_length=20)),
                ("orderCreationTimestamp", models.CharField(max_length=10, null=True)),
                ("updateTimestamp", models.CharField(max_length=9)),
            ],
        ),
    ]
