# Generated by Django 4.1.5 on 2023-09-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "VolvoVehicleOrder",
            "0003_alter_vehiclesearchrequest_actauldeliverydate_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclesearchrequest",
            name="actaulDeliveryDate",
            field=models.CharField(blank=True, default=" ", max_length=10),
        ),
        migrations.AlterField(
            model_name="vehiclesearchrequest",
            name="busarea",
            field=models.CharField(blank=True, default=" ", max_length=10),
        ),
        migrations.AlterField(
            model_name="vehiclesearchrequest",
            name="chassisNo",
            field=models.CharField(blank=True, default=" ", max_length=10),
        ),
        migrations.AlterField(
            model_name="vehiclesearchrequest",
            name="deliveryLocation",
            field=models.CharField(blank=True, default=" ", max_length=20),
        ),
        migrations.AlterField(
            model_name="vehiclesearchrequest",
            name="lastOrderNo",
            field=models.CharField(blank=True, default=" ", max_length=9),
        ),
        migrations.AlterField(
            model_name="vehiclesearchrequest",
            name="modelId",
            field=models.CharField(blank=True, default=" ", max_length=20),
        ),
        migrations.AlterField(
            model_name="vehiclesearchrequest",
            name="orderNo",
            field=models.CharField(blank=True, default=" ", max_length=9),
        ),
        migrations.AlterField(
            model_name="vehiclesearchrequest",
            name="orderStatus",
            field=models.CharField(blank=True, default=" ", max_length=15),
        ),
        migrations.AlterField(
            model_name="vehiclesearchrequest",
            name="orderType",
            field=models.CharField(blank=True, default=" ", max_length=20),
        ),
        migrations.AlterField(
            model_name="vehiclesearchrequest",
            name="requestedBy",
            field=models.CharField(blank=True, default=" ", max_length=20),
        ),
        migrations.AlterField(
            model_name="vehiclesearchrequest",
            name="requestedDeliveryDate",
            field=models.CharField(blank=True, default=" ", max_length=10),
        ),
        migrations.AlterField(
            model_name="vehiclesearchrequest",
            name="vin",
            field=models.CharField(blank=True, default=" ", max_length=20),
        ),
    ]
